### ISSUE TITLE
: Support for the experimental syntax 'decorators' isn't currently enabled (12:1):

### ISSUE THREAD

**Issue by simplenotezy** [jmcdo29/nestjs-graphql-e2e-plugin#8]
Thanks for sharing this repo!

I do have some issues getting the build to run:

```
[Nest] 98926  - 09.08.2024 19.30.34   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
 • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configuration
For information about custom transformations, see:
https://jestjs.io/docs/code-transformation

Details:

SyntaxError: /Users/mf/Projects/kite/backend/src/sync/entities/credentials.entity.ts: Support for the experimental syntax 'decorators' isn't currently enabled (9:1):

   7 | import { Column, Entity, ManyToMany, Relation } from 'typeorm';
   8 |
>  9 | @Entity()
     | ^
  10 | @ObjectType({ description: 'API credentials to access a given platform' })
  11 | export class Credentials {
  12 |   @UuidWithFactory()

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.

If you already added the plugin for this syntax to your config, it's possible that your config isn't being loaded.
You can re-run Babel with the BABEL_SHOW_CONFIG_FOR environment variable to show the loaded configuration:
	npx cross-env BABEL_SHOW_CONFIG_FOR=/Users/mf/Projects/kite/backend/src/sync/entities/credentials.entity.ts <your build command>
See https://babeljs.io/docs/configuration#print-effective-configs for more info.

    at constructor (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parse-error.ts:78:45)
    at Parser.toParseError [as raise] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/tokenizer/index.ts:1496:19)
    at Parser.raise [as expectOnePlugin] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/tokenizer/index.ts:1561:18)
    at Parser.expectOnePlugin [as parseDecorator] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:746:10)
    at Parser.parseDecorator [as parseDecorators] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:727:28)
    at Parser.parseDecorators [as parseStatementLike] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:424:25)
    at Parser.parseStatementLike [as parseModuleItem] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:363:17)
    at Parser.parseModuleItem [as parseBlockOrModuleBlockBody] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:1395:16)
    at Parser.parseBlockOrModuleBlockBody [as parseBlockBody] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:1369:10)
    at Parser.parseBlockBody [as parseProgram] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:217:10)
    at Parser.parseProgram [as parseTopLevel] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/statement.ts:199:25)
    at Parser.parseTopLevel [as parse] (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/parser/index.ts:46:10)
    at parse (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+parser@7.25.0/node_modules/@babel/parser/src/index.ts:65:38)
    at parser (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/parser/index.ts:28:19)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
    at normalizeFile.next (<anonymous>)
    at run (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/transformation/index.ts:39:36)
    at run.next (<anonymous>)
    at transform (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/transform.ts:29:20)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/mf/Projects/kite/backend/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
    at sync (/Users/mf/Projects/kite/backend/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
    at fn (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
    at transformSync (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@babel+core@7.25.2/node_modules/@babel/core/src/transform.ts:66:52)
    at Object.process (/Users/mf/Projects/kite/backend/node_modules/.pnpm/babel-jest@29.7.0_@babel+core@7.25.2/node_modules/babel-jest/build/index.js:273:57)
    at ScriptTransformer.transformSource (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
    at ScriptTransformer._transformAndBuildScript (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
    at ScriptTransformer.transform (/Users/mf/Projects/kite/backend/node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
    at Runtime.transformFile (/Users/mf/Projects/kite/backend/node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1465:53)
    at Runtime._execModule (/Users/mf/Projects/kite/backend/node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1397:34)
    at Runtime._loadModule (/Users/mf/Projects/kite/backend/node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1022:12)
    at Runtime.requireModule (/Users/mf/Projects/kite/backend/node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:882:12)
    at Runtime.requireModuleOrMock (/Users/mf/Projects/kite/backend/node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1048:21)
pt@5.5.4_/src/util/ImportUtils.ts:21:17)kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescri
    at importOrRequireFile (/Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/util/ImportUtils.ts:35:25)
    at /Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/util/DirectoryExportedClassesLoader.ts:57:45
    at async Promise.all (index 2)
    at importClassesFromDirectories (/Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/util/DirectoryExportedClassesLoader.ts:63:18)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/connection/ConnectionMetadataBuilder.ts:92:17)
    at DataSource.buildMetadatas (/Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/data-source/DataSource.ts:710:13)
    at DataSource.initialize (/Users/mf/Projects/kite/backend/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@swc+core@1.7.6_@types+node@20.14.13_typescript@5.5.4_/src/data-source/DataSource.ts:263:13)
```

Any ideas on what I can do here? Happy to share some more code if needed

**Comment by simplenotezy** [comment]
I had to adjust my TypeORM config to not include ".ts" files when searching for entities
